#!/bin/bash
# Setup script for self-hosted Convex
# Usage: scripts/setup-convex.sh [--start]
#   --start: Also start Docker services after setup (default: true)
set -e

# Parse arguments
START_SERVICES="true"
for arg in "$@"; do
    case $arg in
        --no-start)
            START_SERVICES="false"
            shift
            ;;
    esac
done

echo "🔧 Setting up self-hosted Convex..."

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCKER_COMPOSE_FILE="$PROJECT_ROOT/docker-compose.convex.yml"
ENV_FILE="$PROJECT_ROOT/.env.convex.local"

# Detect Coder environment and generate workspace URLs
if [ -n "$CODER" ] && [ -n "$CODER_WORKSPACE_NAME" ]; then
    # Extract protocol and domain from CODER_URL (e.g., https://coder.hahomelabs.com)
    CODER_PROTOCOL="${CODER_URL%%://*}"
    CODER_DOMAIN="${CODER_URL#*//}"

    # Get workspace name and owner from Coder environment
    WORKSPACE_NAME="$CODER_WORKSPACE_NAME"
    USERNAME="${CODER_WORKSPACE_OWNER_NAME:-$USER}"

    # Generate Coder workspace URLs
    # Format: <protocol>://<service>--<workspace>--<owner>.<coder-domain>
    # Example: https://convex-api--convex-ai-chat--jovermier.coder.hahomelabs.com
    CONVEX_API_URL="${CODER_PROTOCOL}://convex-api--${WORKSPACE_NAME}--${USERNAME}.${CODER_DOMAIN}"
    CONVEX_PROXY_URL="${CODER_PROTOCOL}://convex-site--${WORKSPACE_NAME}--${USERNAME}.${CODER_DOMAIN}"
    CONVEX_DASHBOARD_URL="${CODER_PROTOCOL}://convex--${WORKSPACE_NAME}--${USERNAME}.${CODER_DOMAIN}"

    echo "🖥️  Coder workspace detected"
    echo "   Workspace: $WORKSPACE_NAME"
    echo "   Owner: $USERNAME"
    echo "   Domain: $CODER_DOMAIN"
    echo "   Protocol: $CODER_PROTOCOL"
    echo ""
fi

# Determine PostgreSQL URL from environment (prefer DATABASE_URL, fallback to POSTGRES_URI, then POSTGRES_URL)
# Note: We strip the database name from the URL since Convex appends INSTANCE_NAME automatically
# E.g., "postgres://...:5432/app" becomes "postgres://...:5432"
_RAW_POSTGRES_URL="${DATABASE_URL:-${POSTGRES_URI:-${POSTGRES_URL:-}}}"
if [ -n "$_RAW_POSTGRES_URL" ]; then
    # Remove trailing database name (e.g., /app) if present
    _STRIPPED_URL="${_RAW_POSTGRES_URL%/[^/]*}"
    # For Coder PostgreSQL with self-signed certificates, try sslmode=require first
    # If that doesn't work, the connection may need to use sslmode=disable or sslmode=no-verify
    # Note: Rust postgres crate may not accept sslmode parameter in URL, depends on version
    if [[ "$_STRIPPED_URL" == *"?"* ]]; then
        # URL already has query parameters
        POSTGRES_URL="${_STRIPPED_URL}&sslmode=disable"
    else
        # Add query parameters - use disable for self-signed certs
        POSTGRES_URL="${_STRIPPED_URL}?sslmode=disable"
    fi
else
    POSTGRES_URL=""
fi

# Check if PostgreSQL is available (POSTGRES_URL or DATABASE_URL)
if [ -z "$POSTGRES_URL" ]; then
    echo "❌ POSTGRES_URL is not set"
    echo "   Please set DATABASE_URL or POSTGRES_URL in your environment"
    echo ""
    echo "   In Coder workspaces, these variables are automatically provided."
    echo "   For local development, ensure PostgreSQL is running and set the variable."
    exit 1
fi

echo "✅ PostgreSQL database URL configured"

# Set default URLs if not already defined (use Coder-generated URLs if available)
CONVEX_CLOUD_ORIGIN="${CONVEX_CLOUD_ORIGIN:-${CONVEX_API_URL:-http://localhost:3210}}"
CONVEX_SITE_ORIGIN="${CONVEX_SITE_ORIGIN:-${CONVEX_PROXY_URL:-http://localhost:3211}}"
CONVEX_SITE_URL="${CONVEX_SITE_URL:-${CONVEX_API_URL:-http://localhost:3210}}"
CONVEX_DEPLOYMENT_URL="${CONVEX_DEPLOYMENT_URL:-${CONVEX_API_URL:-http://localhost:3210}}"

# Generate .env.convex.local if it doesn't exist or is incomplete
ENV_FILE_MISSING=0
if [ ! -f "$ENV_FILE" ]; then
    echo "📝 Creating $ENV_FILE..."
    ENV_FILE_MISSING=1
else
    # Check if required variables are present
    if ! grep -q "^POSTGRES_URL=" "$ENV_FILE" 2>/dev/null; then
        echo "📝 $ENV_FILE exists but missing POSTGRES_URL, updating..."
        ENV_FILE_MISSING=1
    fi
    if ! grep -q "^CONVEX_CLOUD_ORIGIN=" "$ENV_FILE" 2>/dev/null && [ -n "$CONVEX_API_URL" ]; then
        echo "📝 $ENV_FILE exists but missing Convex URLs, updating..."
        ENV_FILE_MISSING=1
    fi
fi

if [ $ENV_FILE_MISSING -eq 1 ]; then
    # Create or update the env file
    cat > "$ENV_FILE" << EOF
# Self-hosted Convex configuration
# Auto-generated by setup-convex.sh

# PostgreSQL connection URL
POSTGRES_URL=$POSTGRES_URL

# Convex Cloud Origin - External URL for Convex API access
CONVEX_CLOUD_ORIGIN=$CONVEX_CLOUD_ORIGIN

# Convex Site Origin - HTTP actions endpoint (for auth)
CONVEX_SITE_ORIGIN=$CONVEX_SITE_ORIGIN

# Convex Site URL - Used by @convex-dev/auth for provider domain
CONVEX_SITE_URL=$CONVEX_SITE_URL

# Convex Deployment URL
CONVEX_DEPLOYMENT_URL=$CONVEX_DEPLOYMENT_URL
EOF
    echo "✅ Created $ENV_FILE"
fi

# Source environment variables from the (now existing) file
echo "📦 Loading environment variables from $ENV_FILE"
set -a
source "$ENV_FILE"
set +a

export CONVEX_CLOUD_ORIGIN CONVEX_SITE_ORIGIN CONVEX_SITE_URL CONVEX_DEPLOYMENT_URL

# Check if Docker is available
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed or not in PATH"
    exit 1
fi

# Check if docker compose is available
if ! docker compose version &> /dev/null; then
    echo "❌ Docker Compose is not available"
    exit 1
fi

# Start Docker services if requested
if [ "$START_SERVICES" = "true" ]; then
    echo "🚀 Starting Convex Docker services..."
    cd "$PROJECT_ROOT"
    docker compose -f "$DOCKER_COMPOSE_FILE" --env-file "$ENV_FILE" up -d

    echo "⏳ Waiting for Convex backend to be healthy..."
    timeout 60 bash -c 'until docker compose -f "$1" --env-file "$2" ps --format json | grep -q '"'"'healthy'"'"'; do sleep 2; done' _ "$DOCKER_COMPOSE_FILE" "$ENV_FILE"

    echo ""
    echo "✅ Convex services are running!"
    echo ""
    echo "📍 Service URLs:"
    echo "   - Convex API:     ${CONVEX_CLOUD_ORIGIN:-http://localhost:3210}"
    echo "   - Convex Proxy:   ${CONVEX_SITE_ORIGIN:-http://localhost:3211}"
    echo "   - Dashboard:      ${CONVEX_DASHBOARD_URL:-http://localhost:6791}"
    echo ""

    # Get admin key from Docker container
    echo "🔑 Retrieving admin key from Convex container..."
    ADMIN_KEY=$(docker exec convex-backend-local printenv | grep CONVEX_ADMIN_KEY | cut -d= -f2-)

    if [ -n "$ADMIN_KEY" ]; then
        echo "✅ Admin key found: ${ADMIN_KEY:0:20}..."
        echo ""
        echo "⚠️  Add this to your .env.local file:"
        echo "   CONVEX_SELF_HOSTED_ADMIN_KEY=$ADMIN_KEY"
        echo ""
        # Optionally add to .env.convex.local
        if [ -f "$ENV_FILE" ]; then
            if ! grep -q "CONVEX_SELF_HOSTED_ADMIN_KEY" "$ENV_FILE"; then
                echo "CONVEX_SELF_HOSTED_ADMIN_KEY=$ADMIN_KEY" >> "$ENV_FILE"
                echo "✅ Added admin key to $ENV_FILE"
            fi
        fi
    else
        echo "⚠️  Could not retrieve admin key automatically"
        echo "   You may need to generate it manually or check the container logs"
    fi

    echo ""
    echo "📝 Next steps:"
    echo "   1. Update your .env.local with CONVEX_SELF_HOSTED_URL and admin key"
    echo "   2. Run: npx convex dev --configure"
    echo "   3. Select self-hosted deployment when prompted"
    echo "   4. Deploy your functions: npx convex deploy --code"
    echo ""
else
    echo "✅ Setup complete (services not started due to --no-start flag)"
    echo "   Run 'docker compose -f docker-compose.convex.yml up -d' to start services"
    echo ""
fi
